const products = [
  {
    id: 1,
    title: "Bag",
    description: "A stylish leather bag",
    price: 49.99,
    category: "Accessories",
    stock: 10,
    rating: 4,
    discount: 10,
    imageUrl: "./assets/images/static/products/product1.svg",
  },
  {
    id: 2,
    title: "Shoes",
    description: "Comfortable running shoes",
    price: 79.99,
    category: "Footwear",
    stock: 20,
    rating: 5,
    discount: 0,
    imageUrl: "./assets/images/static/products/product2.svg",
  },
  {
    id: 3,
    title: "Watch",
    description: "Elegant wrist watch",
    price: 199.99,
    category: "Accessories",
    stock: 15,
    rating: 4,
    discount: 30,
    imageUrl: "./assets/images/static/products/product3.svg",
  },
  {
    id: 4,
    title: "Sunglasses",
    description: "UV protection sunglasses",
    price: 29.99,
    category: "Accessories",
    stock: 25,
    rating: 4.5,
    discount: 30,
    imageUrl: "./assets/images/static/products/product4.svg",
  },
  {
    id: 5,
    title: "Hat",
    description: "Stylish summer hat",
    price: 19.99,
    category: "Accessories",
    stock: 30,
    rating: 5,
    discount: 0,
    imageUrl: "./assets/images/static/products/product5.svg",
  },
  {
    id: 6,
    title: "Jacket",
    description: "Warm winter jacket",
    price: 99.99,
    category: "Clothing",
    stock: 5,
    rating: 4,
    discount: 0,
    imageUrl: "./assets/images/static/products/product6.svg",
  },
];
