const products = [
  {
    id: 1,
    title: "Backpack Leather Bag",
    description: "Leather Bag with luxurious physical design",
    price: 160.0,
    oldPrice: 140.0,
    isNew: true,
    discount: null,
    rating: 4.8,
    image: "./assets/images/static/products/product1.svg",
  },
  {
    id: 2,
    title: "Shoulder Bag",
    description: "Leather Bag for everyday use",
    price: 540.0,
    oldPrice: 440.0,
    isNew: false,
    discount: 30,
    rating: 4.5,
    image: "./assets/images/static/products/product2.svg",
  },
  {
    id: 3,
    title: "Classic Shoulder Bag",
    description: "Stylish leather bag for daily use",
    price: 360.0,
    oldPrice: 240.0,
    isNew: false,
    discount: 30,
    rating: 4.7,
    image: "./assets/images/static/products/product3.svg",
  },
  {
    id: 4,
    title: "Luxury Shoulder Bag",
    description: "Elegant leather bag with luxurious design",
    price: 420.0,
    oldPrice: 320.0,
    isNew: true,
    discount: null,
    rating: 5.0,
    image: "./assets/images/static/products/product4.svg",
  },
  {
    id: 5,
    title: "Handmade Clutch Bag",
    description: "Luxurious clutch bag made from leather",
    price: 490.0,
    oldPrice: 340.0,
    isNew: false,
    discount: 30,
    rating: 4.6,
    image: "./assets/images/static/products/product5.svg",
  },
  {
    id: 6,
    title: "Classic Backpack",
    description: "Durable and stylish leather backpack",
    price: 400.0,
    oldPrice: 340.0,
    isNew: true,
    discount: null,
    rating: 4.9,
    image: "./assets/images/static/products/product6.svg",
  },
];

export { products };
